# Generated by Django 4.2.4 on 2024-02-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
