# Generated by Django 4.2.4 on 2024-03-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Patient', models.CharField(max_length=200)),
                ('Treatment', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
            ],
        ),
    ]
